### ISSUE TITLE
[BUG] Additional template weekly_workshops does not appear in visual test

### ISSUE THREAD

**Issue by EsmeeIDEMS** [IDEMSInternational/parenting-app-ui#1107]
**Describe the bug**
Even though the template `weekly_workshops` is included in the additional templates to do the visual test on (PR #1095), it does not appear in the folder with screenshots `test-visual-diffs-artifact` (e.g. PR #1102 and #1106). The `home_screen` template does appear.

**App version**
v0.12.2

**Screenshots and videos**
![image](https://user-images.githubusercontent.com/74557272/144636414-e040c17b-4713-41c0-972f-e1da76e1d41d.png)
![image](https://user-images.githubusercontent.com/74557272/144636509-ea0af4e0-8f2f-4d12-b337-ccdc66edff8a.png)
![image](https://user-images.githubusercontent.com/74557272/144636938-13cad6cc-e797-42b4-954e-0ee45154f1ff.png)

**Template**
[weekly_workshops](https://docs.google.com/spreadsheets/d/1tmtdyeSYcqGH6joqZiA-wPtH0QH6td8hA3qGp62AcHs/edit#gid=1277645488)

**Comment by chrismclarke** [comment]
I think that is actually the expected behaviour - the visual-test system only zips files that contains differences so that implies there isn't any difference. Checking the run action I can see it did process the template at least:

![image](https://user-images.githubusercontent.com/10515065/145325487-9bdebcf8-8e5e-4190-bb98-9de95b880109.png)

(can be found deep in the logs of the raw run: https://github.com/IDEMSInternational/parenting-app-ui/actions/runs/1527305763)

So hopefully that should resolve the issue, although if you think there should have been a diff then let me know and I can try deep-dive why it didn't show.

Also if you ever need the full list of source screenshots (generated from the master branch), then they can be found attached to every run in https://github.com/IDEMSInternational/parenting-app-ui/actions/workflows/test-visual-generate.yml

![image](https://user-images.githubusercontent.com/10515065/145325978-b179431a-0b17-4bd6-b9b2-1ad1a2f2728c.png)
