### ISSUE TITLE
[BUG] Pop-ups don't work well with max-height style

### ISSUE THREAD

**Issue by EsmeeIDEMS** [IDEMSInternational/parenting-app-ui#1148]
**Describe the bug**
An image that has a max-height specified in the style list does not display correctly in a pop-up. It seems that the image does not scale, although the "space accounted for the image" does become smaller, which causes components to overlap.

**App version**
v0.13.0 

**To Reproduce**
- Launch the template [example_text_image](https://docs.google.com/spreadsheets/d/1ESiY3It66heuxfPl9PMZuYOKM6jjjpk9qIWH48Q_m-s/edit#gid=2066105506) through the template list
- Launch the template [debug_pop_ups_1](https://docs.google.com/spreadsheets/d/1ESiY3It66heuxfPl9PMZuYOKM6jjjpk9qIWH48Q_m-s/edit#gid=868243677) through the template list and press Button 3 to pop-up the template [example_text_image](https://docs.google.com/spreadsheets/d/1ESiY3It66heuxfPl9PMZuYOKM6jjjpk9qIWH48Q_m-s/edit#gid=2066105506)

**Example template**
[example_text_image](https://docs.google.com/spreadsheets/d/1ESiY3It66heuxfPl9PMZuYOKM6jjjpk9qIWH48Q_m-s/edit#gid=2066105506)
![image](https://user-images.githubusercontent.com/74557272/147273221-4d912df7-16a3-4162-b381-2285602fcfb3.png)

**Screenshots and videos**
![image](https://user-images.githubusercontent.com/74557272/147273264-b565e236-48af-4195-86dc-0a01536316bf.png)
![image](https://user-images.githubusercontent.com/74557272/147273298-ccc802af-f0f5-45b6-9f27-9beeab517ab9.png)

**Comment by chrismclarke** [comment]
Yeah it's a weird style caveat when it comes to having max-height elements nested within max-height elements. When a child can grow to 100% of a parent but the parent can also grow to 100% of another parent then the lowest child loses track of how big it can actually grow and defaults to max size even if that doesn't fit. 

This is a problem particularly in popups as the popup window is of variable size. The quick solution is to change `max-height` to `height` knowing that the image will always want to scale to fill the max-height anyway so the two numbers will essentially be the same.

Longer term a better solution would be to have a better system that automatically passes down the `max-height` style set at the row level directly to the image itself (instead of currently a container that wraps around the image), but that's not easily possible without a larger overhaul of the templating system (reasons it would some take time to explain).

So I've updated the authoring on the example for now, and as I can't see any  other examples in the templates where this is used will close the issue for now

![image](https://user-images.githubusercontent.com/10515065/147283834-39772dca-0794-4d51-b5b9-8c8351a8f362.png)

**Comment by EsmeeIDEMS** [comment]
Happy with this solution for now, thanks!
