### ISSUE TITLE
[BUG] No padding between components in workshop accordion

### ISSUE THREAD

**Issue by EsmeeIDEMS** [IDEMSInternational/parenting-app-ui#1166]
**Describe the bug**
There is no vertical padding between components authored directly within an accordion section of a workshops accordion. However, there IS padding when the content is authored in a nested template.  

**App version**
v0.13.0 

**Debug Template**
[debug_w_accordion_padding
](https://docs.google.com/spreadsheets/d/1AkNZZWGCCwU8olUaoLsAozmZ_7DJaOaEuHOa-LhGci8/edit#gid=669305399)
![image](https://user-images.githubusercontent.com/74557272/149148476-7c2491bd-0648-4abb-8342-385ddcd5ef9c.png)
[debug_w_accordion_section](https://docs.google.com/spreadsheets/d/1AkNZZWGCCwU8olUaoLsAozmZ_7DJaOaEuHOa-LhGci8/edit#gid=615087818)

**Screenshots and videos**
![image](https://user-images.githubusercontent.com/74557272/149148574-fd5eaa6a-cf31-4a38-a36d-0f14e481364a.png)
![image](https://user-images.githubusercontent.com/74557272/149148621-fe5fe238-6c25-45c5-a32f-826621699175.png)

**Additional context**
Low priority as I'm usually authoring the content in separate templates.

**Comment by chrismclarke** [comment]
The workshop accordion is a legacy plh-specific component with a fair few hardcoded styles that are tricky to resolve. As such we now have created a generic accordion component to be used as standard moving forward. I think that instead of applying further fixes to the workshop accordion I would probably suggest it better to just migrate any required functionality over.

Until then I think probably easiest to just fix with manual authoring as required (adding margin-top to components where necessary). Let me know if this seems reasonable to you @EsmeeIDEMS , and if so we can close here
