### ISSUE TITLE
[BUG] No padding between buttons in essential_tool display group

### ISSUE THREAD

**Issue by EsmeeIDEMS** [IDEMSInternational/parenting-app-ui#1195]
**Describe the bug**
There is no padding between buttons in essential_tool display group.

**App version**
v0.13.0

**Debug Template**
[debug_dg_tool 
](https://docs.google.com/spreadsheets/d/19qLXy1PF6BOH9GZ-qpcZJ3-bOfxXAgj7J8H67Nfp9MM/edit#gid=1644996333)

**Screenshots and videos**
![image](https://user-images.githubusercontent.com/74557272/150823314-52a0ca69-d8ff-4385-b5bc-c60265cfaee1.png)

**Comment by chrismclarke** [comment]
Ah, the problem here is that following updates to the style system, consistent styles are only applied when the display group style is `row` or `column` (in cases where left empty `column` is added automatically).

These components have a `tool_1` style which then fails to apply and of the `column` styles (there's no easy way to get one style to extend another). The best fix I can think of this will involve some minor changes on both authoring and dev side, to allow passing multiple styles which can be used to apply multiple sets of formatting (i.e. style=tool_1 column) or similar
