### ISSUE TITLE
[FEATURE] delay_from_activation column for campaigns

### ISSUE THREAD

**Issue by EsmeeIDEMS** [IDEMSInternational/parenting-app-ui#1234]
**What?**
A `delay_from_activation.days` column for campaigns.

**Why?**
Currently we have campaigns (e.g. [campaign_hs_1on1](https://docs.google.com/spreadsheets/d/1pW420PnkUFFtwKqm5JBGIUBAUePOYVb9VV8WQ3UkGNo/edit#gid=1844608978) and [nf_w_1on1](https://docs.google.com/spreadsheets/d/1JXb0lzz8Hztl6K4_3zaUpYrpq9XJjTO7YRPAsx03F-4/edit#gid=142288605)) in which items like 
```
get_field | workshop_day : 0;
get_field | workshop_day : 1;
get_field | workshop_day : 2;
get_field | workshop_day : 3;
get_field | workshop_day : 4;
get_field | workshop_day : 5;
```
appear in the `deactivation_condition` column. This is messy authoring, and has the additional downside that the message remains deactivated until the day it's due, which in the case of a notification means it only gets scheduled if the user enters the app on the due date. Instead, these conditions really try to describe a "delay" from the moment the activation condition first became true. 

**Additional comments**
Up to now I was using (in spreadsheet authoring) the `deactivation_condition` column as simply the negation of the `activation_condition` column, but after this change this would no longer be the case. There are cases where I have a condition like `get_field | w_1on1_completion_level: 100` as an activation condition, which (after this change) really should be a deactivation condition `get_field | w_1on1_completion_level: !100`. I don't think that syntax works currently. 

**Discussion**
David and I discussed how to go about the newly requested interpretation of notifications and this is what we came up with. @chrismclarke If this does not make sense to you we should probably discuss this further.

**Comment by chrismclarke** [comment]
I think you will still have the same problem because we only schedule one notification per campaign. What we really need is batch scheduling (as described previously) and then I _think_ we can use existing schedule delay feature instead of defining this new one. But I can revisit when I look at things later this week/early next

**Comment by chrismclarke** [comment]
In fact delay is a bit of a tricky concept now that I think of, because most campaigns are scheduled around fixed time periods (e.g. every day at 2pm, or every saturday at 7pm), so delaying a notification by a set number of days/hours would push it out of its targetted schedule unless authored very precisely. #1241 is now open so hopefully will provide an alternative to achieve what is required, but if not we can discuss how best to handle

**Comment by EsmeeIDEMS** [comment]
I see your point about delay being tricky. I'll try to achieve what's required using the batch scheduling and a bit of restructuring the spreadsheets.
