### ISSUE TITLE
[FEATURE] Dynamic list variables

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/parenting-app-ui#1246]
**What?**
- [ ] **dynamic data list entries**
Currently the entries in every column of a data list are static, similar to global constants. Previously proposed syntax was to add a prefix `fields::` to a column name to indicate it is dynamic. The entries in this column would be used as the "field default"
- [ ] **(dynamic) list variables**
Currently variables cannot be interpreted as lists. We'd like to have this, and functionality to remove from/add to/clear a list.

**Why?**
Currently I'm using workarounds involving fields, but the proposed would be more powerful and neater.

**Comment by chrismclarke** [comment]
Discussed on call 2022-02-18
No consensus on best way to proceed. Agreed that prefixes aren't ideal as less human-readable, and also that could conflict with the `text::lang` syntax. 
Links back to another issue of how to do things like specify data types for fields (e.g. `Set_field<number>: my_number: 5`) - much of which is currently interpreted or workedaround via `+` operators, and additionally operations on existing data such as `update_field` (particularly is field can be used to save a list.

Possibly may want means of adding a write-layer on top of existing datalists so that a user could override
`@data.workshop.w_self_care.completion_level` via a `set_data | workshop.w_self_care.completion_level` action or similar, and then would just need a syntax to indicate in the data list that the column is writeable (e.g. `completion_level :: default` or `$completion_level` or similar).
