### ISSUE TITLE
[BUG] Content sync on plh_tz deployment deletes tz_sw translation

### ISSUE THREAD

**Issue by EsmeeIDEMS** [IDEMSInternational/parenting-app-ui#1270]
**Describe the bug**
Only when setting the deployment to `plh_global` the translations (audios + text) work as expected. When selecting a different deployment and syncing content, only the English audios + text appear. 

**App version**
v0.14.2

**To Reproduce**
Set deployment to `plh_tz` by running `yarn scripts deployment set`. Sync the content by running `yarn scripts app-data sync`. Observe that only global assets remain, and also all "text" translation files (e.g. `tz_sw.ts`) are deleted.

**Comment by chrismclarke** [comment]
Turns out just to be a minor typo!
![image](https://user-images.githubusercontent.com/10515065/157801147-142d858a-31c3-44f2-a8b0-8b4f9d8bab30.png)

You'll notice that we only have a single string `"tz_en, tz_sw"` not two strings `"tz_en", "tz_sw"` - super hard to pick up as we only validate it is a string, not that it is a particular length, but mystery solved at least. I'll update now and close

**Comment by chrismclarke** [comment]
I've included the fix in #1259
![image](https://user-images.githubusercontent.com/10515065/157801426-9a0ce05f-442a-49e3-9ed4-5be4264aeaf4.png)

**Comment by EsmeeIDEMS** [comment]
Thanks, I should have noticed that!
