### ISSUE TITLE
[BUG] App gets stuck in illustrated stories

### ISSUE THREAD

**Issue by EsmeeIDEMS** [IDEMSInternational/parenting-app-ui#1356]
**Describe the bug**
A handful of users in Tanzania have reported the app "getting stuck" occasionally. All reported cases were inside illustrated stories (which are templates with a lot of nesting).

**App version**
v0.15.2 (TZ deployment) 

**Template Name**
[w_stress_read_1_temp](https://docs.google.com/spreadsheets/d/1GSuUFbGp37daHiVnvIvwRsep5Q0s2Ewy-KnspFVYXrU/edit#gid=1836230481) slide 3/6 - image doesn’t render
[w_money_read_2_temp](https://docs.google.com/spreadsheets/d/18oKsHQ0DZCjpp3yMvesOfkFH9_qERX3HgxnzSV3fIJY/edit#gid=609273714) slide 5/6
[w_rules_read_1_temp](https://docs.google.com/spreadsheets/d/11xU8T23PkdaqPCeWtCuMp_FmJmBz9wQTcFBQxwz0YrI/edit#gid=1836230481) slide 6/8 - image doesn’t render

**Screenshots and videos**
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/74557272/165746449-0599b657-14a0-4818-be2f-02dae7f44624.png)
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/74557272/165746451-ef7b3a69-af8d-445c-91ad-2296c0b3049d.png)
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/74557272/165746453-38494129-f1e4-4949-ae4c-92c143e3f8ed.png)

**Additional context**
Here's some device info from one of the users that was experiencing this issue: 
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/74557272/165745988-2642912f-207c-4ba4-afb5-21eeee60b97b.png)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/74557272/165745970-a28ebdb7-2ec5-4016-b1d9-45d2a60e2dd3.png)

**Comment by EsmeeIDEMS** [comment]
Have not heard that this is occuring to anyone recently (currently v0.16.4) so closing the issue. Can reopen if necessary.

**Comment by EsmeeIDEMS** [comment]
We received a new report of this same issue. 

![Screenshot_20221130_095331](https://user-images.githubusercontent.com/74557272/204749487-9b226747-b743-45be-a8e8-bc666122889c.jpg)

**Comment by chrismclarke** [comment]
Thanks Esmee, the screenshots are really helpful and I think your first suggestion of updating chrome sounds sensible (I'm aware of a few specific issues for chrome v70, wouldn't be surprised if there were also some in v80 as it's a little under 3 years old by now (https://en.wikipedia.org/wiki/Google_Chrome_version_history). 

I can see you've already updated recent crashlytics entries, thanks for doing so. Hopefully when we merge and resolve #1667 that can help speed up the debugging processes too

**Comment by chrismclarke** [comment]
I've taken a closer look at this, and indeed does seem to be a chrome issue.
I downloaded chrome 80 from the link below, which also allows you to run directly from a zip file (no install needed)
https://chromium.cypress.io/win64 - might be of interest if you or @jfmcquade ever want to try recreate issues locally

When running in chrome 80 I get major freezing when proceeding to those parts of the animated sections. Interestingly enough there's no errors in the console, it appears to be a more fundamental problem with how chrome/angular renders the content boxes on the page (screenshot below basically shows 12s taken to try figure out what it should be adding/removing from the page)

If I were to guess, it's likely down to the way the `pair` template adds/removes content boxes, and how we set the value of those content boxes from much higher up. I think depending on processing order we get caught trying to set the value of things that don't exist yet, and chrome gets into a bit of a bad state of not being sure what should or shouldn't be in view.

Updating chrome is one solution, as for whatever reason newer chrome doesn't have the same issues. 

Another solution is to use the `hidden` column instead of the `disabled` column on the [pair template](https://docs.google.com/spreadsheets/d/1ZkAXSGDgCQrDMUbyVVgJrdMUTnuZOicvecP6qytA9sY/edit#gid=1931878555), as this handles content display in a subtly different way (it toggles visibility instead of completely adding/removing elements from the webpage). I think I may have mentioned this a long time back, but essentially for animated sections I'd probably always suggest using `hidden` column instead of `condition` (but for almost everything else `condition` will be more efficient)

I tried making the change and testing locally and indeed it fixed the issue on chrome 80

**Initial screen freeze log**
![image](https://user-images.githubusercontent.com/10515065/204897846-d4b8723b-a89f-4ae1-8229-63eff974baa1.png)

**Comment by chrismclarke** [comment]
Taking another quick look at the authoring, and I can see why there's possibly some confusion. Quite deep nesting with lots of rows called `box_1` or `box_2`. I've also noticed for some nesting reason every time you move to the next slide the page drops down a bit

![image](https://user-images.githubusercontent.com/10515065/204913596-e19c801b-b407-4c4e-a241-278c982af766.png)

I'm not if this is an authoring issue or whether what is authored isn't being displayed in the right way. I'd probably suggest making a low-priority follow-up issue to tidy this up (and ideally create a more simple demo for debugging)
