### ISSUE TITLE
[BUG] Google auth might not be working

### ISSUE THREAD

**Issue by EsmeeIDEMS** [IDEMSInternational/parenting-app-ui#1440]
**Describe the bug**
Elena reported she did not recall being prompted to login with Google when installing the TZ app on her phone. 

To double check, I uninstalled and re-installed the app on my phone to see whether I could reproduce the issue. Indeed I was not asked to login with Google when opening the app, nor did I see the terms and conditions. See screen video below. Not sure if an app uninstall & re-install is technically equivalent to a first install or that it could be that my old app data was still saved somehow? 

**App version**
v0.16.2 TZ

**To Reproduce**
Do a fresh app install, launch app and check whether T&C and Google auth pop up. 

**Screenshots and videos**

https://user-images.githubusercontent.com/74557272/179555511-f24e525f-ca05-48a3-993c-7ea0b9f2e115.mp4

**Comment by ChrisMarsh82** [comment]
This affects the launch screen too

**Comment by jfmcquade** [comment]
I've investigated, and I'm pretty sure that what your video shows above is expected behaviour: the app data is indeed saved or "backed up" in a way that persists over uninstalling and reinstalling the app.

This video (too large to embed on github) shows me starting with a fresh install, getting half way through the launch actions and then backing up my data. Then I uninstall the app and reinstall it (the reinstall happens off-screen rather than via the app store as this is running in emulation). When the app opens again, it picks up where I left off, halfway through the launch actions. This is because the fields that store whether or not the user has viewed/dismissed a particular launch action are included in the data that gets backed up, and this data persists after an app has been uninstalled. If I don't run the back up before uninstalling, on reinstall the launch actions start from the beginning.

Video: https://user-images.githubusercontent.com/64838927/179743752-5f9e240f-a5fd-41a1-9fb5-84977373933d.mov

We do have control over whether this data persists, i.e. whether or not we allow our app data to be backed up. But it seems right to back it up in general – it's good for the user if they can reinstall without losing their data (workshop completions etc). If we did want to force the launch actions to be reset on uninstall and reinstall, we could look into ways of doing that. But I don't think it would be trivial and it doesn't seem crucial. Possible routes for achieving this: 
1. Explicitly exclude the fields that track whether launch actions have been completed from the backup
2. Link each of these fields to the specific instance of the app


In terms of the Google Auth not showing generally, I've been unable to replicate that. On my personal phone, the TZ app does prompt me to sign in with Google and it works as expected. In order to test on your device, you can delete the app data for the TZ app and then relaunch it. Here's a video of me doing that process on my phone:

https://user-images.githubusercontent.com/64838927/179752217-e2668bcb-7de1-489a-a898-663bb0c08e25.mov

At the beginning of the video, I've already signed in and so the app doesn't prompt the Google Auth on launch. But after deleting the app data, it does.

**Comment by EsmeeIDEMS** [comment]
Thank you Johnny. I just checked on my phone, deleting the app data, and indeed I was getting the Google Authentication (just like you). Will ask Elena to try on hers and close this issue if she confirms this works for her.
