### ISSUE TITLE
[FEATURE] Globals depending on skin

### ISSUE THREAD

**Issue by EsmeeIDEMS** [IDEMSInternational/parenting-app-ui#1528]
**What?**
A couple of global variables depend on the selected skin or theme. For example, the global constant `@global.weekly_workshop` should evaluate to "Weekly Workshop" in the workshop skin and to "Module" in case the modular skin is selected. 

<img width="438" alt="image" src="https://user-images.githubusercontent.com/74557272/193592717-54b0df21-eb86-4d33-8320-a10dc00d3620.png">

[home_screen_variables](https://docs.google.com/spreadsheets/d/1qNzL5selRW2Pzu74UAj7rz6d-blAnhQodm-dC1uChMI/edit#gid=0)

I'm not sure if it would make most sense to use globals for this or fields. Also, I'm not sure when this re-evaluation should take place.

**Comment by EsmeeIDEMS** [comment]
This can probably be done with the overrides system, @EsmeeIDEMS to try. Not clear whether order of overrides and translation will work (workshop --> module --> Kiswahili word for module)

**Comment by jfmcquade** [comment]
Global overrides can be applied base on the value of the current `_app_skin`, analogously to how they are applied for languages, see [example_overrides](https://docs.google.com/spreadsheets/d/1MpoH3BxhECZRmYM10HZ0pTOoe69FJ-fEW9FwzK-Q6yw/edit#gid=1745157248). 

However, from some testing and reviewing the code, it appears that the case of 2 global overrides that have the same target is not currently explicitly handled. This means that, currently, the global override flow sheets are processed in _alphabetical order_ by `flow_name`. So whichever global override flow sheet with a `flow_name` that comes latest alphabetically will be applied last, and therefore trump the others.

This is shown in the example below, where the override based on the current skin trumps the override based on the language code, because in this case the override sheets have the names `example_glob_override_modular` and `example_glob_override_es_sp` respectively, and the former name comes after the latter alphabetically.

https://user-images.githubusercontent.com/64838927/193802776-d6838100-ce1a-4fd1-8d86-4e78f3308892.mov

The logs for when the skin is "modular" and the language is changed to "es_sp". Note that the override `example_glob_override_default -> example_glob_override_es_sp` is applied and _then_ the override `override example_glob_override_default -> example_glob_override_modular` is applied

<img width="500" alt="Screenshot 2022-10-04 at 11 51 48" src="https://user-images.githubusercontent.com/64838927/193802960-26e5c6d9-ebe0-4e0d-98b8-b17c0d83b2f6.png">

**Comment by jfmcquade** [comment]
I've just had a look at the current sheets, and I think the use case you're describing might not be a problem.
Currently the string "Weekly Workshops" gets translated, but this doesn't use an override. The translations of the string exist and are applied at the same point as other translations. So if the value of the global was instead "Modules", then the translation should still be applied provided one exists for the target language.

There may be other cases where we want to apply global overrides with the same target based on, for example, skin and language independently, which would need some extra work, but I think the case you've outlined here is achievable without anything extra.
