### ISSUE TITLE
[BUG] Display group introduces extra LHS padding

### ISSUE THREAD

**Issue by EsmeeIDEMS** [IDEMSInternational/parenting-app-ui#1710]
**Describe the bug**
Some display group styles seem to introduce extra padding on the LHS of the screen. This causes the components inside it to be off-centre. 

**App version**
v0.16.9

**Template Names**
- [x] 1. [feature_display_group](https://docs.google.com/spreadsheets/d/1ARbNRGDer5vj9qSpRMZFrMkYifGkH3TLtDVp72YbaqU/edit#gid=1231713195)
<img width="228" alt="image" src="https://user-images.githubusercontent.com/74557272/211365511-6e04e586-b8c7-466e-8e1d-8c6725e78390.png">

- [ ] 2. For example, see [w_money_read_2_temp](https://docs.google.com/spreadsheets/d/18oKsHQ0DZCjpp3yMvesOfkFH9_qERX3HgxnzSV3fIJY/edit#gid=609273714) - In this case I'm not sure if the padding is introduced by the display group or by the animated section...
![image](https://user-images.githubusercontent.com/74557272/211364355-4a177fc7-6956-4923-9713-fa56b17afee1.png)

**Comment by jfmcquade** [comment]
It turns out that these are unrelated issues:

1. [feature_display_group](https://docs.google.com/spreadsheets/d/1ARbNRGDer5vj9qSpRMZFrMkYifGkH3TLtDVp72YbaqU/edit#gid=1231713195)

Here, the `display_group` components that were displaying off-centre had additional styles specified in the `style_list` column, which added additional margins. Whilst specifying a margin like this in the template should add a margin all the way round the component, these additional margin styles combined with other styling applied to display groups to have the effect of shifting the element to the right.
Whilst we should be able to handle the case of adding margins as a style specified from the template level, assuming that we don't currently do this in the app (outside of this feature template), I don't think it's worth fixing. Adding custom styles generally is discouraged, and we should work to achieve any template-level styling via `style: style_name` _parameters_.
I have removed these margin styles from the [feature_display_group](https://docs.google.com/spreadsheets/d/1ARbNRGDer5vj9qSpRMZFrMkYifGkH3TLtDVp72YbaqU/edit#gid=1231713195) template. See screenshots below for before and after states of the spreadsheet and the corresponding rendered templates. (Perhaps the whole `style_list` column could be removed from this template? I wonder why the custom styles are there at all)

<img width="1200" alt="Screenshot 2023-01-11 at 14 43 22" src="https://user-images.githubusercontent.com/64838927/211859798-43a81e92-f7dd-420c-bd8a-7f82f56943c6.png">
<img width="800" alt="Screenshot 2023-01-11 at 14 44 11" src="https://user-images.githubusercontent.com/64838927/211859898-e7640176-f6ca-403c-aab5-4147173932a0.png">


2. E.g. [w_money_read_2_temp](https://docs.google.com/spreadsheets/d/18oKsHQ0DZCjpp3yMvesOfkFH9_qERX3HgxnzSV3fIJY/edit#gid=609273714)
This should be fixed by PR #1715

**Comment by EsmeeIDEMS** [comment]
Thanks Johnny that makes sense. I agree item (1) is not an issue in that case. Sorry for not having checked the template...
