### ISSUE TITLE
[BUG] User ID on one mobile device is the same across apps

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/parenting-app-ui#1865]
**Describe the bug**
On my phone my user id is the same (`22cec921d274c703`) on the WASH App, ParentApp TZ and ParentApp ZA. 

This is problematic in particular because this ID is used as an identifier in the [App Users](https://apps-server.idems.international/dashboard/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjZ9LCJ0eXBlIjoicXVlcnkifSwiZGlzcGxheSI6InRhYmxlIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319) table on Metabase. Therefore, syncs from all three apps write to the same row of this table. 

**App version**
v0.16.5

**To Reproduce**
Install ParentApp TZ and ParentApp ZA on a mobile device. Navigate through the side menu to **Settings** > **Your ParentApp Code**. Observe that this shows the same code on both apps. 

**Template Name**
[user_code](https://docs.google.com/spreadsheets/d/1iSG1kzK4OTHcoiwWoZ25LZxrJqERg2_iP9369HTi_bQ/edit#gid=1630264062)

**Screenshots and videos**
ParentApp ZA (screenshot + Metabase entry)
![WhatsApp Image 2023-03-23 at 16 09 47](https://user-images.githubusercontent.com/74557272/227265579-54e475b8-ca18-413b-a52b-0dee0db6d41a.jpeg)
<img width="630" alt="image" src="https://user-images.githubusercontent.com/74557272/227265783-64e2c4dc-971f-4304-adec-6e759619b891.png">

ParentApp TZ (screenshot + Metabase entry)
![WhatsApp Image 2023-03-23 at 16 13 32](https://user-images.githubusercontent.com/74557272/227266653-1ee0c066-e923-4cfd-a0f4-a42f0fe39443.jpeg)
<img width="617" alt="image" src="https://user-images.githubusercontent.com/74557272/227266828-669ac7ef-6871-49cb-97de-40c3e962d0c7.png">

**Comment by chrismclarke** [comment]
I've taken a deeper look into this one. The ID is generated using the [Capacitor Device plugin](https://capacitorjs.com/docs/apis/device#deviceid), which describes the property as

> The UUID of the device as available to the app. This identifier may change on modern mobile platforms that only allow per-app install UUIDs. On web, a random identifier is generated and stored on localStorage for subsequent calls. If localStorage is not available a new random identifier will be generated on every call.

This suggests that it should be unique per app installed (and potentially even reset on app reinstall), however digging deeper into the actual implementation code I can see it calls a property from Android settings secure [Android_ID](https://developer.android.com/reference/android/provider/Settings.Secure#ANDROID_ID) which states the value should be:
> On Android 8.0 (API level 26) and higher versions of the platform, a 64-bit number (expressed as a hexadecimal string), unique to each combination of app-signing key, user, and device

and
> In versions of the platform lower than Android 8.0 (API level 26), a 64-bit number (expressed as a hexadecimal string) that is randomly generated when the user first sets up the device and should remain constant for the lifetime of the user's device
https://developer.android.com/reference/android/provider/Settings.Secure#ANDROID_ID

So that means on Android 8+ the app id should be unique across apps as the app-signing key is unique (google play store manages individual keys for us on a per-app level), so doesn't make sense to me why you see the same id. Reading around a little it seems that there is inconsistencies with this property, it actually depends on the manufacturer to implement and not strictly enforced:
https://stackoverflow.com/questions/4799394/is-secure-android-id-unique-for-each-device
