### ISSUE TITLE
Component Value Handling

### ISSUE THREAD

**Issue by egor-mir** [IDEMSInternational/parenting-app-ui#488]
Add ability to update local variable when the value or parameter of component fire change.
Formats: 
- "@local.{template_component_name}.value"
- "@local.{template_component_name}.{parameter_list_parameter_name}"

Example:
- User choose option "Sad" in ComboBox component
- After choosing a value we update local variable @local.combo_box_1.value
- After updating @local.combo_box_1.value we change text field value because we take it from @local.combo_box_1.value

**Comment by volloholic** [comment]
Really glad you are looking at this. There is a lot of detail to get right here, I share some comments.
This should ideally not be mixed in with the local variable handling as then it would not be available within nested templates. 
@chrismclarke might want to come in to discuss how this should relate to the internal storage he is implementing.
Possibility Formats for value include:
-"@{template_component_name}"
-"@{template_component_name}._value"
-"@Component.{template_component_name}._value"
It will be important to get these details right so key principles:
-@local is not the right place for this as that only lives at a single level in the templating system. 
-to get the levels navigating right we will almost certainly need to nest this within nested properties so a common use might be: "@{nested_template_name}.{nested_template_name}.{template_component_name}._value" This is important because the same screen may have multiple instances of the component which would only be differentiated through their nesting. Draft example of this in welcome_survey_q_5
-Internally set properties are generally labeled with an _ so _value rather than value is preferable

It's not clear to me that we have a justified use case to include other parameters yet but it would be great functionality if we could get it right. I guess there would be an additional layer of nesting.
-"@{template_component_name}.{parameter_list}.{parameter_name}"

**Comment by chrismclarke** [comment]
I think there's still some unresolved discussions around the local variables, namespacing, inheritance etc., but for now I'd expect that type of functionality to work with the existing actions system we have (if not, I'd be keen to first get a better understanding of why it doesn't work). 

The current limitation would be how to define these actions in the authoring. If I remember correctly the excel sheets have a single row that describes the combo-box and all options, and so any `click` action will by default be placed on the parent container of the combo box, and so do the same thing regardless of a specific option picked. I would suggest short term we decide on the default behaviour that we want from these combo boxes, and then provide more functionality for authors via parameters for the immediate use cases (e.g. `saveSelectedAsField : some_local_field`)

Longer term it would probably make more sense to use the actions row, and provide a syntax for authors to use to refer to the value that was clicked in the combo box (e.g. `click | set_field | some_field:$value_of_clicked_box`)

**Comment by smborio** [comment]
Here's the example: https://docs.google.com/spreadsheets/d/1D8w8_nJ6M9f5Q0bjfeReEmiwvE-umKprFFdeohoNRXs/edit?usp=sharing

The texts should be what is in the comments column.

**Comment by chrismclarke** [comment]
Discussed again with David today, we both had a strong preference for the use of local variables as proposed by @egor-mir  (e.g. @local.template_component_name), but will likely make the value the default return instead of being explicitly required (no current use-cases for needing to access other columns from the data right now)

I'll make the changes to the local variable handling so that alll component values are made available within local variables, and then hand back over to implement in components that require it.
