### ISSUE TITLE
[BUG] Non-display items in display groups create empty spaces

### ISSUE THREAD

**Issue by smborio** [IDEMSInternational/parenting-app-ui#925]
**Describe the bug**
If you have a display group where an element inside it is a set variable of any kind, then it takes up a blank space. We have a workaround for this by adding a flex:0 in the style_list but this should be the default behaviour when something that hasn’t got a display element is included in a display group

**App version**
0.10.2

**To Reproduce**
This can be seen in the debug template [debug_dg_var](https://docs.google.com/spreadsheets/d/19qLXy1PF6BOH9GZ-qpcZJ3-bOfxXAgj7J8H67Nfp9MM/edit#gid=297544613&range=A20). Compare dg_3 and dg_4.

**Debug Template**
[debug_dg_var](https://docs.google.com/spreadsheets/d/19qLXy1PF6BOH9GZ-qpcZJ3-bOfxXAgj7J8H67Nfp9MM/edit#gid=297544613&range=A20). The workaround is shown in dg_4. 

**Screenshots and videos**
<img src="https://user-images.githubusercontent.com/46322225/127374772-7b890c28-af07-47b3-a546-9e5fb9428ece.png" width="300px">

**Comment by zulkifelff** [comment]
Within the awkwardly spaced display group, there is vacant space due to the 'set_variable' type. We have introduced a check that will restrict the rendering of 'set_variable'.

![debug_dg_var_1](https://user-images.githubusercontent.com/45070594/129191874-3ea2f06e-3414-48c7-9131-2cdc48db6a39.png)


If that seems to be the appropriate solution to this issue, please do comment, and afterward, we will create PR against this issue.

**Comment by ehmadzubair** [comment]
@chrismclarke @EsmeeIDEMS

**Comment by chrismclarke** [comment]
That's definitely the core issue, will be interested to see how you implement the fix to prevent rendering. @zulkifelff feel free to tag me in the PR review when you open it
