### ISSUE TITLE
[BUG] Tours can't read from data lists

### ISSUE THREAD

**Issue by EsmeeIDEMS** [IDEMSInternational/parenting-app-ui#966]
**Describe the bug**
Tours can't read from data lists: when using a data list item in a tour, it displays as **undefined**. 

**App version**
v0.11.1 (and before)

**Debug sheets**
template: [debug_tour_template ](https://docs.google.com/spreadsheets/d/1CQzsurOr4egC706cx_Fvkk5Zfvl-vRmd-Pu40mYM1qA/edit#gid=1916689711)
tour: [debug_tour](https://docs.google.com/spreadsheets/d/1CQzsurOr4egC706cx_Fvkk5Zfvl-vRmd-Pu40mYM1qA/edit#gid=95491335)

**To reproduce**
Launch debug_tour_template (note that the data item prints correctly here). Click the button to start the debug_tour. The second step in the tour shows the data item not working. 

**Screenshots**
![image](https://user-images.githubusercontent.com/74557272/130603577-df031866-5c02-4b2e-a46b-229862301164.png)
![image](https://user-images.githubusercontent.com/74557272/130602620-195a7643-0f9b-4edc-9996-23430676974c.png)

**Comment by chrismclarke** [comment]
Yes, as mentioned in #988 the tour service implements its own barebones implementation of template content with custom support only for global variables (not field, data, conditional, calc etc.). 

We will need to update it so the rows are processed by the template service, which could take a bit of refactoring given how currently processing is linked with rendering and not easily handled standalone (due to things nesting, which are more easily delegated for child templates to handle when they are ready for render themselves)

I can think of 2 possible shorter term solutions that might work:
1. If all we need are datalists we just hardcode that aspect as another hack solution
2. We attempt to render the tour content through are existing templating system

Will probably hold off work on this issue until we decide best means forward on a call
